version: 2.1
jobs:
  test:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run: $(npm bin)/cypress run

workflows:
  version: 2
  primary:
    jobs:
      - test
